name: calc
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # You can adjust the version as needed
    - name: Install dependencies
      run: npm install
 
    - name: install jest 
      run: npm install --save-dev jest

    - name: run unit test 
      run: npm run test

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Depcheck
      uses: dependency-check/Dependency-Check_Action@main
      with:
          project: 'Calculator'
          path: '.'
          format: 'HTML'
          out: 'reports'
    - name: Upload Test results
      uses: actions/upload-artifact@master
      with:
          name: Depcheck report
          path: ${{github.workspace}}/reports
    #- name: SonarCloud Scan
      #uses: SonarSource/sonarcloud-github-action@master
      #env:
       # SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #with:
        #args: >
          #-Dsonar.projectKey=Mahidharigs_Calculator
          #-Dsonar.organization=Mahidharigs
   # - name: Build project
     # run: npm run build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: mahidharigs/calculator:calc
    - name: Run Docker image
      run: |
          docker run --name myapp -d -p 80:80 mahidharigs/calculator:calc
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
          login-server: calculatorazure.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push an image to Azure Container Registry
      run: |
          docker build . -t calculatorazure.azurecr.io/calc:${{ github.sha }}
          docker push calculatorazure.azurecr.io/calc:${{ github.sha }}
     # - name: Deploy to Azure App Service
     # uses: azure/webapps-deploy@v2
     # with:
         # app-name: 'calculatorigs'
         # slot-name: 'production'
         # publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
         # images: 'mahidharigs/calculator:calc'

          
      
          
